1-2 Примеры создания массивов

In [13]:
import numpy as np

lst = [1, 2, 6, 3 , 9586, 'urhw']
arr1 = np.array(lst)
print("массив из списка 1: ", arr1)

lst2 = [1, 2, 6, 3]
arr12 = np.array(lst2)
print("массив из списка 2: ", arr12)

# zeros (заполняет нулями)
arr2 = np.zeros(10)
print("массив из нулей: ", arr2)

# ones (заполняет единицами)
arr3 = np.ones((6, 3))
print("Массив из единиц:")
print( arr3)

# arange
arr4 = np.arange(0, 100, 11)
print("Массив с помощью arange: ", arr4)

# другие
print()
arr5 = np.full((5, 3), 9) # заполняет числом
print(arr5)
print()
arr6 = np.zeros_like(arr3) # такой же формы
print(arr6)

массив из списка 1:  ['1' '2' '6' '3' '9586' 'urhw']
массив из списка 2:  [1 2 6 3]
массив из нулей:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Массив из единиц:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Массив с помощью arange:  [ 0 11 22 33 44 55 66 77 88 99]

[[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3 Демонстрация атрибутов

In [14]:
print("Форма:", arr5.shape)
print("Тип данных:", arr5.dtype)


Форма: (5, 3)
Тип данных: int64


4 Примеры индексирования и срезов

In [18]:
arr = np.arange(0, 400).reshape((20, 20))

el = arr[3, 3]
print("получение отдельного элемента:", el)

sr = arr[4:9, 8:15]
print("извлечение подмассива с помощью среза:", sr)
print(sr.shape)

получение отдельного элемента: 63
извлечение подмассива с помощью среза: [[ 88  89  90  91  92  93  94]
 [108 109 110 111 112 113 114]
 [128 129 130 131 132 133 134]
 [148 149 150 151 152 153 154]
 [168 169 170 171 172 173 174]]
(5, 7)


5 Примеры векторных операций и базовых статистик

In [22]:
a = np.array([67, 23, 89, 54])
b = np.arange(56, 100, 14)

# поэлементное сложение
print("a + b =", a + b)
# умножение массивов
print("a * b =", a * b)

print("Средняя величина:", a.mean())
print("Сумма:", a.sum())
print("Минимальное:", a.min())
print("Максимальное:", a.max())

a + b = [123  93 173 152]
a * b = [3752 1610 7476 5292]
Средняя величина: 58.25
Сумма: 233
Минимальное: 23
Максимальное: 89
